[project]
name = "lime"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gurobipy>=13.0.1",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
]
